/** Visible copy from case-study/COPY_MAP.md — keep short. */
export const copy = {
  brand: "CareerOS",
  subline: "A job-search operating system.",
  anti: [
    "Not a mass-apply bot.",
    "Not an AI that invents a career.",
    "Not a guaranteed interview machine.",
  ],
  humanSubmits: "Human submits.",
  act1: "ACT 01 — The Broken Job Hunt",
  toolsCaption: "Eight tools. Zero workflow.",
  misreads: "One profile. Many misreads.",
  fitSkills: "Fit isn’t only skills.",
  fragmented: "Fragmented.",
  fragmentedSub: "The work wasn’t hard. The system was.",
  origin:
    "After 17 July 2026, an existing job-search frustration became urgent — searching, filtering, rewriting, and paying for fragmented tools on repeat.",
  act2: "ACT 02 — The Investigation",
  decisionEngine: "It started as a decision engine — not a resume builder.",
  twenty: "Only ~20% is the valuable work.",
  twentyDisclaimer: "Illustrative split — not a measured KPI.",
  twentyHuman: "Judgment · Truthful materials",
  control: "Control is a feature.",
  whatExists: "So what already exists?",
  act3: "ACT 03 — Existing Landscape",
  oneSlice: "Each solves one slice.",
  nobodyOwns: "Nobody owns the workflow.",
  act4: "ACT 04 — The Philosophy",
  thesis: "Generate resumes that sell you truthfully.",
  pEvidence: "Evidence before generation.",
  pHuman: "Human in the loop.",
  pScore: "Transparent scoring.",
  pTitle: "No invented seniority.",
  beliefsEngine: "Beliefs need an engine.",
  act5: "ACT 05 — The Engine",
  aiAdvises: "AI advises. Rules authorize.",
  thingItself: "Now — the thing itself.",
  engineNote:
    "Early keyword matching produced obviously wrong fit scores — LLM judgement arrived to read meaning, while hard filters stayed deterministic.",
  act6: "ACT 06 — The Product",
  pipelineGlance: "Pipeline at a glance.",
  batchHuman: "Batch in. Human chooses.",
  explainable: "Explainable multi-factor fit.",
  rolesEnd: "Some roles end here.",
  reviewBefore: "Review before the world sees it.",
  twoArtifacts: "Same pipeline. Two artifacts.",
  trackSent: "Track what you sent. Submit stays outside.",
  underGlass: "Under the glass — engineering.",
  act7: "ACT 07 — Engineering",
  stackForbids: "The interesting part isn’t the stack. It’s what the stack forbids.",
  trustNote:
    "The resume engine took many iterations before a document felt trusted enough to submit — editorial quality, not a single catastrophic failure.",
  act8: "ACT 08 — What changed how I build",
  authDull: "Generation can be creative. Authorization must be dull.",
  persist: "If it isn’t persisted, it isn’t the workflow.",
  docsDrift: "Docs drift. Code decides.",
  noEvidence: "NO EVIDENCE",
  tellTruth: "Build systems that tell the truth — especially about themselves.",
  is: "Personal job-search OS · Evidence-first · Human-in-the-loop",
  isnt: "Mass apply · Multi-tenant SaaS · Visa advice",
  commits: "Six commits. Jul 24 → Aug 4, 2026.",
  explore: "Explore the system.",
  credit: "CareerOS · Evidence before generation.",
  scope: "Production-ready for one operator — not distribution-ready SaaS.",
} as const;

export const ACTS = [
  { id: "cold-open", label: "Open" },
  { id: "act-1", label: "Broken Hunt" },
  { id: "act-2", label: "Investigation" },
  { id: "act-3", label: "Landscape" },
  { id: "act-4", label: "Philosophy" },
  { id: "act-5", label: "Engine" },
  { id: "act-6", label: "Product" },
  { id: "act-7", label: "Engineering" },
  { id: "act-8", label: "What Changed" },
  { id: "close", label: "Close" },
] as const;
